import { 
  Ship, 
  Container, 
  Briefcase, 
  Anchor, 
  Zap, 
  Shield,
  Clock,
  Globe,
  Award,
  Users,
  FileCheck,
  Search,
  ClipboardCheck,
  FileText,
  Send,
  Scale
} from "lucide-react"

// Iconos para servicios
export const serviceIcons = {
  Ship: Ship,
  Container: Container,
  Briefcase: Briefcase,
  Anchor: Anchor,
  Drone: Zap,
}

// Iconos del proceso
export const processIcons = {
  Search: Search,
  ClipboardCheck: ClipboardCheck,
  FileCheck: FileCheck,
  FileText: FileText,
  Send: Send,
}

// Iconos de ventajas
export const advantageIcons = {
  Shield: Shield,
  Clock: Clock,
  Award: Award,
  Globe: Globe,
  FileCheck: FileCheck,
  Users: Users,
}

// Iconos de casos de éxito
export const caseIcons = {
  Container: Container,
  Ship: Ship,
  Shield: Shield,
  Scale: Scale,
}

// Datos completos de servicios en tres idiomas (basados en company-info.txt)
export const servicesData = {
  es: {
    hero: {
      title: "Servicios de Inspección Marítima",
      subtitle: "Excelencia técnica para la industria marítima global",
      description: "Soluciones integrales de inspección, supervisión y consultoría para armadores, fletadores, aseguradoras y operadores portuarios en todo el mundo.",
      cta: "Solicitar Cotización",
      ctaSecondary: "Contacto 24/7",
    },
    stats: {
      title: "Respaldados por Resultados",
      subtitle: "Métricas que demuestran nuestro compromiso con la excelencia",
      items: [
        { value: "+480", label: "Servicios Completados", desc: "Proyectos e inspecciones desde 2019" },
        { value: "+120", label: "Clientes Corporativos", desc: "Armadores, operadores y aseguradoras" },
        { value: "78%", label: "Tasa de Recurrencia", desc: "Clientes que repiten servicios" },
        { value: "95%", label: "Satisfacción", desc: "Según retroalimentación post-servicio" },
        { value: "24-72h", label: "Tiempo de Entrega", desc: "Informes según complejidad" },
        { value: "24/7", label: "Disponibilidad", desc: "Respuesta de emergencia global" },
      ],
    },
    services: {
      title: "Nuestros Servicios",
      subtitle: "Soluciones completas para cada necesidad marítima",
      filterAll: "Todos",
      filterVessel: "Buques",
      filterCargo: "Carga",
      filterConsultancy: "Consultoría",
      filterPort: "Puertos",
      items: {
        vessel: {
          title: "Inspecciones de Buques",
          shortDesc: "Evaluaciones integrales para armadores, fletadores y aseguradoras",
          description: "Inspecciones integrales de buques para armadores, fletadores, aseguradoras y operadores portuarios. Evaluaciones objetivas, precisas y conformes a estándares internacionales.",
          features: [
            { name: "Inspecciones Precompra", desc: "Inspección integral antes de adquirir un buque, cubriendo casco, maquinaria, equipos y documentación." },
            { name: "Inspecciones de Condición y Clase", desc: "Evaluación del estado del buque y estimación del valor de mercado para aseguradoras, bancos y propietarios." },
            { name: "Inspecciones On-hire / Off-hire", desc: "Inspección del estado del buque y/o cantidades de combustible al inicio o final de contrato de fletamento." },
            { name: "Inspecciones de Daños y Siniestros", desc: "Evaluación de integridad estructural, motores, sistemas de propulsión y equipos mecánicos tras incidentes." },
            { name: "Inspecciones P&I", desc: "Inspecciones para Clubes de Protección e Indemnización centradas en seguridad y condición general del buque." },
          ],
          icon: "Ship",
          image: "/images/footage/IMG_20181207_111709.webp",
        },
        cargo: {
          title: "Inspecciones a la Carga",
          shortDesc: "Verificación técnica para prevenir reclamaciones",
          description: "Verificación y evaluación técnica de carga para prevenir reclamaciones y determinar responsabilidades. Servicios especializados para diferentes tipos de carga marítima.",
          features: [
            { name: "Inspecciones Pre-embarque y Descarga", desc: "Verificación de carga, estiba y operaciones para prevenir reclamaciones contractuales." },
            { name: "Evaluación de Daños en Carga", desc: "Determinación de causa, alcance, circunstancias y responsabilidad asociada a daños durante el transporte." },
            { name: "Supervisión de Carga y Descarga", desc: "Monitoreo de operaciones de manipulación para garantizar seguridad y cumplimiento normativo." },
            { name: "Evaluación de Carga Suelta y Contenedores", desc: "Inspección de carga fraccionada a granel, carga proyecto y verificación de contenedores refrigerados." },
            { name: "Inspección por Calados (Draft Survey)", desc: "Método hidrostático preciso para calcular peso de carga a granel midiendo el desplazamiento del buque." },
            { name: "Servicios de Conteo (Tally)", desc: "Conteo físico y verificación de carga embarcada o recibida para control de inventario." },
          ],
          icon: "Container",
          image: "/images/footage/IMG_20190405_150150.webp",
        },
        consultancy: {
          title: "Consultoría Marítima",
          shortDesc: "Asesoramiento experto y auditorías de cumplimiento",
          description: "Asesoramiento experto y auditorías de cumplimiento para garantizar operaciones seguras y conformes a normativas internacionales.",
          features: [
            { name: "Auditorías IGS/PBIP/MLC", desc: "Auditorías de cumplimiento que cubren requisitos de seguridad, protección marítima y normas laborales." },
            { name: "Asesoría Técnica", desc: "Asesoramiento experto sobre operaciones del buque, mantenimiento y fallas operativas o mecánicas." },
            { name: "Investigación de Incidentes", desc: "Investigaciones independientes de accidentes marítimos con análisis de causas raíz." },
            { name: "Consultoría de Cumplimiento Normativo", desc: "Asistencia para cumplir con instrumentos de la OMI, requisitos de Estado de Bandera y reglas de sociedades de clasificación." },
          ],
          icon: "Briefcase",
          image: "/images/footage/IMG_20190406_095637.webp",
        },
        port: {
          title: "Servicios de Puertos y Terminales",
          shortDesc: "Evaluaciones de infraestructura portuaria",
          description: "Evaluaciones de infraestructura portuaria y condiciones de seguridad para garantizar operaciones seguras y eficientes.",
          features: [
            { name: "Evaluaciones de Condición de Terminales", desc: "Evaluación integral de infraestructura portuaria y condiciones de seguridad en terminales." },
            { name: "Inspecciones de Atraque y Amarre", desc: "Evaluación de sistemas de amarre, defensas y la idoneidad del muelle para operaciones seguras." },
          ],
          icon: "Anchor",
          image: "/images/footage/IMG_20190406_172726.webp",
        },
        specialized: {
          title: "Servicios Especializados",
          shortDesc: "Tecnología de vanguardia para inspecciones",
          description: "Tecnología de vanguardia para inspecciones en áreas de difícil acceso, mejorando la precisión y eficiencia de nuestras evaluaciones.",
          features: [
            { name: "Inspecciones Aéreas con Drones", desc: "Inspecciones aéreas de áreas del buque de difícil acceso utilizando tecnología UAV de última generación." },
          ],
          icon: "Drone",
          image: "/images/footage/IMG_20190506_163718.webp",
        },
      },
    },
    process: {
      title: "Nuestro Proceso",
      subtitle: "Metodología probada para resultados excepcionales",
      steps: [
        { icon: "Search", title: "Solicitud y Análisis", desc: "Recibimos su solicitud, analizamos los requerimientos específicos y definimos el alcance del servicio." },
        { icon: "ClipboardCheck", title: "Planificación", desc: "Asignamos inspectores certificados y coordinamos la logística para la inspección en el puerto designado." },
        { icon: "FileCheck", title: "Ejecución", desc: "Realizamos la inspección siguiendo protocolos internacionales y mejores prácticas de la industria." },
        { icon: "FileText", title: "Informe Técnico", desc: "Elaboramos informes detallados con evidencia fotográfica, hallazgos y recomendaciones técnicas." },
        { icon: "Send", title: "Entrega y Soporte", desc: "Entregamos el informe en 24-72 horas y ofrecemos soporte continuo para aclaraciones o seguimiento." },
      ],
    },
    successCases: {
      title: "Casos de Éxito",
      subtitle: "Resultados que respaldan nuestra experiencia",
      cases: [
        { title: "Inspección de Carga a Granel", client: "Operador Logístico Internacional", challenge: "Discrepancias recurrentes en peso y condición de la carga generaban disputas contractuales.", solution: "Draft survey completo, supervisión de carga/descarga y registro fotográfico documental.", result: "Eliminación de reclamos contractuales y ahorro económico significativo para el cliente.", icon: "Container" },
        { title: "Survey Pre-Charter", client: "Operador de Flota", challenge: "Incertidumbre sobre la condición real del buque antes de formalizar el fletamento.", solution: "Inspección estructural y operativa completa con checklists bajo estándares internacionales.", result: "Negociación contractual ajustada a la realidad técnica del buque.", icon: "Ship" },
        { title: "Cumplimiento Normativo", client: "Operador Portuario", challenge: "Observaciones recurrentes en auditorías que comprometían la operación de la terminal.", solution: "Diagnóstico normativo completo y elaboración de plan de acción correctivo.", result: "Cumplimiento total alcanzado en la auditoría posterior.", icon: "Shield" },
        { title: "Asistencia en Reclamo Marítimo", client: "Aseguradora", challenge: "Falta de evidencia técnica clara para resolver disputa sobre daños.", solution: "Peritaje técnico independiente con análisis detallado de causas.", result: "Resolución favorable del reclamo basada en evidencia técnica objetiva.", icon: "Scale" },
      ],
    },
    certifications: {
      title: "Estándares y Certificaciones",
      subtitle: "Cumplimiento riguroso con normativas internacionales",
      description: "Todas nuestras operaciones se encuentran alineadas con los más altos estándares de la industria marítima:",
      items: [
        { name: "ISO 9001:2015", desc: "Sistema de Gestión de Calidad" },
        { name: "IMO SOLAS", desc: "Convenio Internacional para la Seguridad de la Vida Humana en el Mar" },
        { name: "MARPOL", desc: "Convenio Internacional para Prevenir la Contaminación por los Buques" },
        { name: "MLC 2006", desc: "Convenio sobre el Trabajo Marítimo" },
        { name: "Código ISM", desc: "Código Internacional de Gestión de la Seguridad" },
        { name: "PBIP/ISPS", desc: "Código Internacional para la Protección de Buques y Puertos" },
        { name: "Estado de Bandera", desc: "Requisitos de Administraciones Marítimas Nacionales" },
        { name: "Sociedades de Clasificación", desc: "Reglas y estándares de sociedades clasificadoras" },
      ],
    },
    whyChooseUs: {
      title: "¿Por Qué Elegirnos?",
      subtitle: "Ventajas que nos distinguen en el mercado",
      items: [
        { icon: "Shield", title: "Verificación Independiente", desc: "Informes objetivos de tercera parte aceptados por todas las partes interesadas en la industria." },
        { icon: "Clock", title: "Respuesta Rápida 24/7", desc: "Disponibilidad global inmediata para inspecciones de emergencia en cualquier puerto del mundo." },
        { icon: "Award", title: "Inspectores Certificados", desc: "Profesionales con amplia experiencia en arquitectura naval, ingeniería marítima y operaciones portuarias." },
        { icon: "Globe", title: "Cobertura Global", desc: "Red de servicios desarrollada para atender puertos comerciales, terminales y fondeaderos internacionales." },
        { icon: "FileCheck", title: "Informes de Alto Valor", desc: "Documentación técnica con valor probatorio, fotografías detalladas y recomendaciones expertas." },
        { icon: "Users", title: "Enfoque en el Cliente", desc: "Soluciones personalizadas y servicio excepcional con comunicación clara en cada etapa." },
      ],
    },
    faq: {
      title: "Preguntas Frecuentes",
      subtitle: "Respuestas a las consultas más comunes sobre nuestros servicios",
      items: [
        { question: "¿En qué puertos ofrecen servicios de inspección?", answer: "MSC ofrece cobertura global con presencia en los principales puertos comerciales, terminales y fondeaderos. Nuestra red permite movilización rápida a cualquier ubicación requerida por el cliente." },
        { question: "¿Cuánto tiempo tarda en entregarse el informe de inspección?", answer: "Nuestro tiempo promedio de entrega es de 24 a 72 horas, dependiendo de la complejidad del servicio. Para situaciones de emergencia, ofrecemos informes preliminares en tiempos más reducidos." },
        { question: "¿Qué certificaciones tienen sus inspectores?", answer: "Nuestros inspectores y consultores son profesionales certificados en arquitectura naval, ingeniería marítima, operaciones portuarias, ciencias náuticas y derecho marítimo, con más de 25 años de experiencia combinada." },
        { question: "¿Ofrecen servicios de inspección de emergencia?", answer: "Sí, contamos con disponibilidad 24/7 para inspecciones de emergencia. Puede contactarnos a través de nuestra línea directa (+507) 65980679 para coordinar atención inmediata." },
        { question: "¿Los informes son aceptados por aseguradoras y clubes P&I?", answer: "Sí, nuestros informes técnicos son imparciales y objetivos, cumpliendo con los estándares requeridos por aseguradoras P&I, Hull & Machinery, y demás partes interesadas de la industria." },
        { question: "¿Qué tipos de carga pueden inspeccionar?", answer: "Inspeccionamos carga a granel (sólida y líquida), carga general, contenedores (incluyendo refrigerados), carga proyecto y breakbulk. Cada tipo de carga es evaluado con metodologías específicas." },
      ],
    },
    cta: {
      title: "¿Listo para Comenzar?",
      subtitle: "Nuestro equipo está preparado para movilizarse a cualquier puerto del mundo",
      description: "Contáctenos para una cotización sin compromiso o para coordinar una inspección de emergencia.",
      primary: "Solicitar Cotización",
      secondary: "Emergencia 24/7",
      phone: "(+507) 65980679",
      email: "msc@mscsurveyors.org",
    },
  },
  en: {
    hero: {
      title: "Marine Survey Services",
      subtitle: "Technical excellence for the global maritime industry",
      description: "Comprehensive inspection, supervision, and consultancy solutions for shipowners, charterers, insurers, and port operators worldwide.",
      cta: "Request Quote",
      ctaSecondary: "24/7 Contact",
    },
    stats: {
      title: "Backed by Results",
      subtitle: "Metrics that demonstrate our commitment to excellence",
      items: [
        { value: "+480", label: "Services Completed", desc: "Projects and inspections since 2019" },
        { value: "+120", label: "Corporate Clients", desc: "Shipowners, operators, and insurers" },
        { value: "78%", label: "Recurrence Rate", desc: "Clients who repeat services" },
        { value: "95%", label: "Satisfaction", desc: "Based on post-service feedback" },
        { value: "24-72h", label: "Delivery Time", desc: "Reports based on complexity" },
        { value: "24/7", label: "Availability", desc: "Global emergency response" },
      ],
    },
    services: {
      title: "Our Services",
      subtitle: "Complete solutions for every maritime need",
      filterAll: "All",
      filterVessel: "Vessels",
      filterCargo: "Cargo",
      filterConsultancy: "Consultancy",
      filterPort: "Ports",
      items: {
        vessel: {
          title: "Vessel Surveys",
          shortDesc: "Comprehensive assessments for shipowners, charterers, and insurers",
          description: "Comprehensive vessel inspections for shipowners, charterers, insurers, and port operators. Objective, accurate assessments compliant with international standards.",
          features: [
            { name: "Pre-purchase Surveys", desc: "Comprehensive inspection before acquiring a vessel, covering hull, machinery, equipment, and documentation." },
            { name: "Condition and Class Surveys", desc: "Assessment of vessel condition and market value estimation for insurers, banks, and owners." },
            { name: "On-hire / Off-hire Surveys", desc: "Inspection of vessel condition and/or fuel quantities at the start or end of charter contract." },
            { name: "Damage and Casualty Surveys", desc: "Assessment of structural integrity, engines, propulsion systems, and mechanical equipment after incidents." },
            { name: "P&I Surveys", desc: "Surveys for Protection & Indemnity Clubs focused on safety and general condition of the vessel." },
          ],
          icon: "Ship",
          image: "/images/footage/IMG_20181207_111709.webp",
        },
        cargo: {
          title: "Cargo Surveys",
          shortDesc: "Technical verification to prevent claims",
          description: "Technical verification and assessment of cargo to prevent claims and determine responsibilities. Specialized services for different types of maritime cargo.",
          features: [
            { name: "Pre-loading & Discharge Surveys", desc: "Verification of cargo, stowage, and operations to prevent contractual claims." },
            { name: "Cargo Damage Assessment", desc: "Determination of cause, extent, circumstances, and responsibility associated with damage during transport." },
            { name: "Loading & Discharging Supervision", desc: "Monitoring of handling operations to ensure safety and regulatory compliance." },
            { name: "Breakbulk & Container Evaluation", desc: "Inspection of bulk cargo, project cargo, and verification of refrigerated containers." },
            { name: "Draft Survey", desc: "Precise hydrostatic method to calculate bulk cargo weight by measuring vessel displacement." },
            { name: "Tally Services", desc: "Physical counting and verification of shipped or received cargo for inventory control." },
          ],
          icon: "Container",
          image: "/images/footage/IMG_20190405_150150.webp",
        },
        consultancy: {
          title: "Marine Consultancy",
          shortDesc: "Expert advice and compliance audits",
          description: "Expert advice and compliance audits to ensure safe operations and compliance with international regulations.",
          features: [
            { name: "ISM/ISPS/MLC Audits", desc: "Compliance audits covering safety requirements, maritime security, and labor standards." },
            { name: "Technical Advisory", desc: "Expert advice on vessel operations, maintenance, and operational or mechanical failures." },
            { name: "Incident Investigation", desc: "Independent investigations of maritime accidents with root cause analysis." },
            { name: "Regulatory Compliance Consulting", desc: "Assistance to comply with IMO instruments, Flag State requirements, and Classification Society rules." },
          ],
          icon: "Briefcase",
          image: "/images/footage/IMG_20190406_095637.webp",
        },
        port: {
          title: "Port & Terminal Services",
          shortDesc: "Port infrastructure assessments",
          description: "Port infrastructure assessments and safety conditions to ensure safe and efficient operations.",
          features: [
            { name: "Terminal Condition Assessments", desc: "Comprehensive evaluation of port infrastructure and safety conditions in terminals." },
            { name: "Berth and Mooring Surveys", desc: "Assessment of mooring systems, fenders, and berth suitability for safe operations." },
          ],
          icon: "Anchor",
          image: "/images/footage/IMG_20190406_172726.webp",
        },
        specialized: {
          title: "Specialized Services",
          shortDesc: "Cutting-edge technology for inspections",
          description: "Cutting-edge technology for inspections in hard-to-reach areas, improving the accuracy and efficiency of our assessments.",
          features: [
            { name: "Drone Aerial Surveys", desc: "Aerial inspections of hard-to-reach vessel areas using state-of-the-art UAV technology." },
          ],
          icon: "Drone",
          image: "/images/footage/IMG_20190506_163718.webp",
        },
      },
    },
    process: {
      title: "Our Process",
      subtitle: "Proven methodology for exceptional results",
      steps: [
        { icon: "Search", title: "Request & Analysis", desc: "We receive your request, analyze specific requirements, and define the scope of service." },
        { icon: "ClipboardCheck", title: "Planning", desc: "We assign certified surveyors and coordinate logistics for the inspection at the designated port." },
        { icon: "FileCheck", title: "Execution", desc: "We conduct the inspection following international protocols and industry best practices." },
        { icon: "FileText", title: "Technical Report", desc: "We prepare detailed reports with photographic evidence, findings, and technical recommendations." },
        { icon: "Send", title: "Delivery & Support", desc: "We deliver the report within 24-72 hours and provide ongoing support for clarifications or follow-up." },
      ],
    },
    successCases: {
      title: "Success Stories",
      subtitle: "Results that support our expertise",
      cases: [
        { title: "Bulk Cargo Inspection", client: "International Logistics Operator", challenge: "Recurring discrepancies in cargo weight and condition generated contractual disputes.", solution: "Complete draft survey, loading/discharging supervision, and documentary photographic record.", result: "Elimination of contractual claims and significant financial savings for the client.", icon: "Container" },
        { title: "Pre-Charter Survey", client: "Fleet Operator", challenge: "Uncertainty about the actual condition of the vessel before formalizing the charter.", solution: "Complete structural and operational inspection with checklists under international standards.", result: "Contract negotiation adjusted to the technical reality of the vessel.", icon: "Ship" },
        { title: "Regulatory Compliance", client: "Port Operator", challenge: "Recurring observations in audits that compromised terminal operations.", solution: "Complete regulatory assessment and development of corrective action plan.", result: "Full compliance achieved in subsequent audit.", icon: "Shield" },
        { title: "Maritime Claim Assistance", client: "Insurance Company", challenge: "Lack of clear technical evidence to resolve dispute over damages.", solution: "Independent technical expert assessment with detailed cause analysis.", result: "Favorable resolution of the claim based on objective technical evidence.", icon: "Scale" },
      ],
    },
    certifications: {
      title: "Standards and Certifications",
      subtitle: "Rigorous compliance with international regulations",
      description: "All our operations are aligned with the highest standards of the maritime industry:",
      items: [
        { name: "ISO 9001:2015", desc: "Quality Management System" },
        { name: "IMO SOLAS", desc: "International Convention for the Safety of Life at Sea" },
        { name: "MARPOL", desc: "International Convention for the Prevention of Pollution from Ships" },
        { name: "MLC 2006", desc: "Maritime Labour Convention" },
        { name: "ISM Code", desc: "International Safety Management Code" },
        { name: "ISPS Code", desc: "International Ship and Port Facility Security Code" },
        { name: "Flag State", desc: "National Maritime Administration Requirements" },
        { name: "Classification Societies", desc: "Rules and standards of classification societies" },
      ],
    },
    whyChooseUs: {
      title: "Why Choose Us?",
      subtitle: "Advantages that distinguish us in the market",
      items: [
        { icon: "Shield", title: "Independent Verification", desc: "Objective third-party reports accepted by all industry stakeholders." },
        { icon: "Clock", title: "Rapid 24/7 Response", desc: "Immediate global availability for emergency inspections at any port worldwide." },
        { icon: "Award", title: "Certified Surveyors", desc: "Professionals with extensive experience in naval architecture, marine engineering, and port operations." },
        { icon: "Globe", title: "Global Coverage", desc: "Service network developed to serve international commercial ports, terminals, and anchorages." },
        { icon: "FileCheck", title: "High-Value Reports", desc: "Technical documentation with evidentiary value, detailed photographs, and expert recommendations." },
        { icon: "Users", title: "Client Focus", desc: "Customized solutions and exceptional service with clear communication at every stage." },
      ],
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Answers to the most common questions about our services",
      items: [
        { question: "At which ports do you offer inspection services?", answer: "MSC offers global coverage with presence in major commercial ports, terminals, and anchorages. Our network allows rapid mobilization to any location required by the client." },
        { question: "How long does it take to deliver the inspection report?", answer: "Our average delivery time is 24 to 72 hours, depending on the complexity of the service. For emergency situations, we offer preliminary reports in shorter timeframes." },
        { question: "What certifications do your surveyors have?", answer: "Our surveyors and consultants are certified professionals in naval architecture, marine engineering, port operations, nautical sciences, and maritime law, with over 25 years of combined experience." },
        { question: "Do you offer emergency inspection services?", answer: "Yes, we have 24/7 availability for emergency inspections. You can contact us through our direct line (+507) 65980679 to coordinate immediate attention." },
        { question: "Are reports accepted by insurers and P&I clubs?", answer: "Yes, our technical reports are impartial and objective, meeting the standards required by P&I insurers, Hull & Machinery, and other industry stakeholders." },
        { question: "What types of cargo can you inspect?", answer: "We inspect bulk cargo (solid and liquid), general cargo, containers (including refrigerated), project cargo, and breakbulk. Each type of cargo is evaluated with specific methodologies." },
      ],
    },
    cta: {
      title: "Ready to Get Started?",
      subtitle: "Our team is ready to mobilize to any port worldwide",
      description: "Contact us for a no-obligation quote or to coordinate an emergency inspection.",
      primary: "Request Quote",
      secondary: "24/7 Emergency",
      phone: "(+507) 65980679",
      email: "msc@mscsurveyors.org",
    },
  },
  zh: {
    hero: {
      title: "海事检验服务",
      subtitle: "为全球海事行业提供技术卓越",
      description: "为全球船东、租船人、保险公司和港口运营商提供全面的检验、监督和咨询解决方案。",
      cta: "请求报价",
      ctaSecondary: "24/7联系",
    },
    stats: {
      title: "以结果为证",
      subtitle: "证明我们对卓越承诺的指标",
      items: [
        { value: "+480", label: "完成服务", desc: "自2019年以来的项目和检验" },
        { value: "+120", label: "企业客户", desc: "船东、运营商和保险公司" },
        { value: "78%", label: "回头率", desc: "重复使用服务的客户" },
        { value: "95%", label: "满意度", desc: "基于服务后反馈" },
        { value: "24-72小时", label: "交付时间", desc: "根据复杂程度的报告" },
        { value: "24/7", label: "可用性", desc: "全球紧急响应" },
      ],
    },
    services: {
      title: "我们的服务",
      subtitle: "满足每种海事需求的完整解决方案",
      filterAll: "全部",
      filterVessel: "船舶",
      filterCargo: "货物",
      filterConsultancy: "咨询",
      filterPort: "港口",
      items: {
        vessel: {
          title: "船舶检验",
          shortDesc: "为船东、租船人和保险公司提供全面评估",
          description: "为船东、租船人、保险公司和港口运营商提供全面的船舶检验。符合国际标准的客观、准确评估。",
          features: [
            { name: "购前检验", desc: "购买船舶前的全面检验，涵盖船体、机械、设备和文件。" },
            { name: "状况和船级检验", desc: "为保险公司、银行和船东评估船舶状况和市场价值。" },
            { name: "租入/租出检验", desc: "在租船合同开始或结束时检验船舶状况和/或燃油数量。" },
            { name: "损坏和事故检验", desc: "事故后评估结构完整性、发动机、推进系统和机械设备。" },
            { name: "P&I检验", desc: "为保赔协会进行的检验，重点关注船舶的安全和总体状况。" },
          ],
          icon: "Ship",
          image: "/images/footage/IMG_20181207_111709.webp",
        },
        cargo: {
          title: "货物检验",
          shortDesc: "防止索赔的技术验证",
          description: "货物的技术验证和评估，以防止索赔和确定责任。为不同类型的海运货物提供专业服务。",
          features: [
            { name: "装货前和卸货检验", desc: "验证货物、积载和操作，以防止合同索赔。" },
            { name: "货物损坏评估", desc: "确定运输过程中损坏的原因、程度、情况和相关责任。" },
            { name: "装卸监督", desc: "监控货物处理操作，确保安全和法规合规。" },
            { name: "散杂货和集装箱评估", desc: "散装货物、项目货物检验和冷藏集装箱验证。" },
            { name: "水尺检验", desc: "通过测量船舶排水量计算散装货物重量的精确水静力学方法。" },
            { name: "理货服务", desc: "对装运或接收货物进行实物清点和验证，用于库存控制。" },
          ],
          icon: "Container",
          image: "/images/footage/IMG_20190405_150150.webp",
        },
        consultancy: {
          title: "海事咨询",
          shortDesc: "专家建议和合规审核",
          description: "专家建议和合规审核，确保安全运营并符合国际法规。",
          features: [
            { name: "ISM/ISPS/MLC审核", desc: "涵盖安全要求、海上安保和劳工标准的合规审核。" },
            { name: "技术咨询", desc: "关于船舶操作、维护和操作或机械故障的专家建议。" },
            { name: "事故调查", desc: "海事事故的独立调查和根本原因分析。" },
            { name: "法规合规咨询", desc: "协助遵守IMO文件、船旗国要求和船级社规则。" },
          ],
          icon: "Briefcase",
          image: "/images/footage/IMG_20190406_095637.webp",
        },
        port: {
          title: "港口和码头服务",
          shortDesc: "港口基础设施评估",
          description: "港口基础设施评估和安全条件，确保安全高效的运营。",
          features: [
            { name: "码头状况评估", desc: "港口基础设施和码头安全条件的全面评估。" },
            { name: "泊位和系泊检验", desc: "评估系泊系统、护舷和泊位对安全操作的适用性。" },
          ],
          icon: "Anchor",
          image: "/images/footage/IMG_20190406_172726.webp",
        },
        specialized: {
          title: "专业服务",
          shortDesc: "检验的尖端技术",
          description: "用于难以到达区域检验的尖端技术，提高我们评估的准确性和效率。",
          features: [
            { name: "无人机航空检验", desc: "使用最先进的无人机技术对船舶难以到达区域进行航空检验。" },
          ],
          icon: "Drone",
          image: "/images/footage/IMG_20190506_163718.webp",
        },
      },
    },
    process: {
      title: "我们的流程",
      subtitle: "经过验证的方法论带来卓越成果",
      steps: [
        { icon: "Search", title: "请求与分析", desc: "我们收到您的请求，分析具体要求，并确定服务范围。" },
        { icon: "ClipboardCheck", title: "规划", desc: "我们分配认证检验师并协调指定港口检验的物流。" },
        { icon: "FileCheck", title: "执行", desc: "我们按照国际协议和行业最佳实践进行检验。" },
        { icon: "FileText", title: "技术报告", desc: "我们准备详细的报告，包括照片证据、发现和技术建议。" },
        { icon: "Send", title: "交付与支持", desc: "我们在24-72小时内交付报告，并为澄清或后续跟进提供持续支持。" },
      ],
    },
    successCases: {
      title: "成功案例",
      subtitle: "支持我们专业知识的成果",
      cases: [
        { title: "散装货物检验", client: "国际物流运营商", challenge: "货物重量和状况的反复差异导致合同纠纷。", solution: "完整的水尺检验、装卸监督和文件照片记录。", result: "消除合同索赔，为客户节省大量资金。", icon: "Container" },
        { title: "租前检验", client: "船队运营商", challenge: "在正式签订租船合同前对船舶实际状况的不确定性。", solution: "按国际标准进行完整的结构和操作检验及检查表。", result: "合同谈判与船舶技术实际情况相符。", icon: "Ship" },
        { title: "法规合规", client: "港口运营商", challenge: "审核中反复出现的观察意见影响码头运营。", solution: "完整的法规评估和纠正行动计划的制定。", result: "在随后的审核中实现完全合规。", icon: "Shield" },
        { title: "海事索赔协助", client: "保险公司", challenge: "缺乏明确的技术证据来解决损害纠纷。", solution: "独立技术专家评估和详细原因分析。", result: "基于客观技术证据的有利索赔解决。", icon: "Scale" },
      ],
    },
    certifications: {
      title: "标准与认证",
      subtitle: "严格遵守国际法规",
      description: "我们所有的运营都符合海事行业的最高标准：",
      items: [
        { name: "ISO 9001:2015", desc: "质量管理体系" },
        { name: "IMO SOLAS", desc: "国际海上人命安全公约" },
        { name: "MARPOL", desc: "国际防止船舶造成污染公约" },
        { name: "MLC 2006", desc: "海事劳工公约" },
        { name: "ISM规则", desc: "国际安全管理规则" },
        { name: "ISPS规则", desc: "国际船舶和港口设施安保规则" },
        { name: "船旗国", desc: "国家海事管理局要求" },
        { name: "船级社", desc: "船级社的规则和标准" },
      ],
    },
    whyChooseUs: {
      title: "为什么选择我们？",
      subtitle: "使我们在市场上脱颖而出的优势",
      items: [
        { icon: "Shield", title: "独立验证", desc: "被所有行业利益相关者接受的客观第三方报告。" },
        { icon: "Clock", title: "24/7快速响应", desc: "全球任何港口紧急检验的即时可用性。" },
        { icon: "Award", title: "认证检验师", desc: "在造船、轮机工程和港口运营方面拥有丰富经验的专业人员。" },
        { icon: "Globe", title: "全球覆盖", desc: "为国际商业港口、码头和锚地服务的网络。" },
        { icon: "FileCheck", title: "高价值报告", desc: "具有证据价值的技术文件、详细照片和专家建议。" },
        { icon: "Users", title: "以客户为中心", desc: "定制解决方案和卓越服务，每个阶段都有清晰的沟通。" },
      ],
    },
    faq: {
      title: "常见问题",
      subtitle: "关于我们服务最常见问题的解答",
      items: [
        { question: "你们在哪些港口提供检验服务？", answer: "MSC在主要商业港口、码头和锚地提供全球覆盖。我们的网络允许快速调动到客户要求的任何地点。" },
        { question: "检验报告需要多长时间交付？", answer: "我们的平均交付时间为24至72小时，取决于服务的复杂程度。对于紧急情况，我们提供更短时间内的初步报告。" },
        { question: "你们的检验师有哪些认证？", answer: "我们的检验师和顾问是造船、轮机工程、港口运营、航海科学和海事法律领域的认证专业人员，拥有超过25年的综合经验。" },
        { question: "你们提供紧急检验服务吗？", answer: "是的，我们提供24/7紧急检验服务。您可以通过我们的直线电话(+507) 65980679联系我们协调即时服务。" },
        { question: "报告是否被保险公司和P&I俱乐部接受？", answer: "是的，我们的技术报告公正客观，符合P&I保险公司、船体机械保险公司和其他行业利益相关者的要求标准。" },
        { question: "你们可以检验哪些类型的货物？", answer: "我们检验散装货物（固体和液体）、普通货物、集装箱（包括冷藏）、项目货物和散杂货。每种类型的货物都用特定方法评估。" },
      ],
    },
    cta: {
      title: "准备好开始了吗？",
      subtitle: "我们的团队随时准备前往世界任何港口",
      description: "联系我们获取免费报价或协调紧急检验。",
      primary: "请求报价",
      secondary: "24/7紧急热线",
      phone: "(+507) 65980679",
      email: "msc@mscsurveyors.org",
    },
  },
}

export type Language = "es" | "en" | "zh"
export type ServicesDataType = typeof servicesData.es

